services:
  db:
    image: postgres:15-alpine
    container_name: bookmaster_db
    env_file:
      - compose.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: bookmaster_redis

  web:
    build: .
    container_name: bookmaster_web
    env_file:
      - compose.env
    environment:
      BUNDLE_WITHOUT: ""
      BUNDLE_DEPLOYMENT: "0"
      RAILS_MAX_THREADS: 5
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    command: ./bin/rails server -b 0.0.0.0

  worker:
    build: .
    container_name: bookmaster_worker
    env_file:
      - compose.env
    environment:
      BUNDLE_WITHOUT: ""
      BUNDLE_DEPLOYMENT: "0"
      RAILS_MAX_THREADS: 5
    depends_on:
      - db
      - redis
    volumes:
      - .:/rails
    command: bundle exec sidekiq

  frontend:
    build: ./frontend
    container_name: bookmaster_frontend
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000
    depends_on:
      - web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
  node_modules:


