AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'frontend/**'
    - 'node_modules/**'
    - '**/node_modules/**'
    - 'vendor/**'

plugins:
  - rubocop-rails
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
